# Generated by Django 3.0.2 on 2020-01-10 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория заметок',
                'verbose_name_plural': 'Категории заметок',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое заметки')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('uuid', models.UUIDField(blank=True, null=True, verbose_name='Уникальный ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Category', verbose_name='Категория заметок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зам')),
            ],
            options={
                'verbose_name': 'Заметка пользователя',
                'verbose_name_plural': 'Заметки пользователей',
            },
        ),
    ]
